sudo: required
services:
  - docker

before_script:
  - docker pull $DOCKER_USERNAME/$DOCKER_IMAGE || true

script:
  - ./bin/build.sh -d

after_script:
  - docker images

before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";

deploy:
  provider: script
  script: docker push $DOCKER_USERNAME/$DOCKER_IMAGE
  on:
    branch: staging
