version: '3.4'
services:
  db_development:
    build:
      context: .
      dockerfile: DOCKERFILE.db.development
    image: bhgrant/bhg_ho_database
    ports:
      - 5439:5432
    environment:
      - POSTGRES_PASSWORD
      - DATABASE_OWNER
      - TEAM_PASSWORD
  api_development:
    build:
      context: .
      dockerfile: DOCKERFILE.api.development
    image: bhgrant/bhg_ho_django
    command: ./bin/development-docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - PROJECT_NAME
      - DEBUG=True
      - POSTGRES_USER
      - POSTGRES_NAME
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_PASSWORD
      - DJANGO_SECRET_KEY
